version: '3.8'

services:
  terraform:
    image:
      public.ecr.aws/l2m0t2f1/terraform-mfa:latest

    volumes:
      - workspace-data:/workspace
      - terraform-home:/home/terraform

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

volumes:
  workspace-data:
  terraform-home: