version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::525658500115:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-6RWZ2AS62OZB"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::525658500115:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-YK70AVF0KB5I"
cloudformation_execution_role = "arn:aws:iam::525658500115:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-PU0PHR4XEYIQ"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-1emqvhjubmdin"
image_repository = "525658500115.dkr.ecr.ap-northeast-1.amazonaws.com/aws-sam-cli-managed-dev-pipeline-resources-imagerepository-zyi8ckn3hrrs"
region = "ap-northeast-1"

[prd.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::525658500115:role/aws-sam-cli-managed-prd-pipe-PipelineExecutionRole-19TDACPYND1VS"
cloudformation_execution_role = "arn:aws:iam::525658500115:role/aws-sam-cli-managed-prd-p-CloudFormationExecutionR-17LCDRBA28KKI"
artifacts_bucket = "aws-sam-cli-managed-prd-pipeline-artifactsbucket-1t57t4plc57oq"
image_repository = "525658500115.dkr.ecr.ap-northeast-1.amazonaws.com/aws-sam-cli-managed-prd-pipeline-resources-imagerepository-tw70enbevmiu"
region = "ap-northeast-1"
